site_name: 厦门大学·RoboMaster·代码说明
site_favicon: favicon.ico
site_url: 
nav:
- Overview:
    - Introduction: README.md
    - Hardware Support: Hardware-Support.md
- Basic:
    - Software Install: Software-Install.md
    - Getting Started: Getting-Started.md
    - Motor Control: Motor-Control.md
- FAQs:
    - How to Debug: How-to-Debug.md

    
theme: readthedocs
site_author: ASR-Crash
copyright: Copyright © 2021 ASR-Crash